# Copyright 2017 Istio Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

##################################################################################################
# Spring-based Reviews backend
##################################################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v4
    spec:
      containers:
      - name: reviews
        image: gcr.io/nathanmittler-istio-test/reviews-v4:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
---
##################################################################################################
# Direct all Reviews traffic to v4
##################################################################################################
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-traffic-split-rule
spec:
  destination:
    name: reviews
  route:
  - labels:
      version: v1
    weight: 0
  - labels:
      version: v2
    weight: 0
  - labels:
      version: v3
    weight: 0
  - labels:
      version: v4
    weight: 100
---
##################################################################################################
# Spring-based Ratings backend
##################################################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ratings-v4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ratings
        version: v4
    spec:
      containers:
      - name: ratings
        image: gcr.io/nathanmittler-istio-test/ratings-v4:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
---
##################################################################################################
# Split Ratings traffic between v1 and v2
##################################################################################################
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ratings-traffic-split-rule
spec:
  destination:
    name: ratings
  route:
  - labels:
      version: v1
    weight: 50
  - labels:
      version: v4
    weight: 50
